models:
  classifier : "models/stage_1_rf_classifier_pipeline.pkl"
  regressor : "models/stage_2_rf_regressor_pipeline.pkl"

ui:
  default_inputs:
    no_of_dependents: 3
    education: Graduate 
    self_employed: No
    income_annum: 100000
    loan_amount: 10000000
    loan_term: 12
    cibil_score: 600
    residential_assets_value: 5000000
    commercial_assets_value: 97345
    luxury_assets_value: 45198
    bank_asset_value: 435345